/*Práctica SELECT INTO
Realiza los siguientes ejemplos. Usa %ROWTYPE y %TYPE
1. PRÁCTICA 1
• Crear un bloque PL/SQL que devuelva al salario máximo del 
departamento 100 y lo deje en una variable denominada salario_maximo 
y la visualice*/
SET SERVEROUTPUT ON
DECLARE
    SALARIO_MAXIMO NUMBER;
BEGIN
    SELECT MAX(SALARY) INTO SALARIO_MAXIMO FROM EMPLOYEES WHERE DEPARTMENT_ID = 100;

    DBMS_OUTPUT.PUT_LINE(SALARIO_MAXIMO);
END;
/*2. PRÁCTICA2
• Visualizar el tipo de trabajo del empleado número 100*/
SET SERVEROUTPUT ON
DECLARE
    TIPO_TRABAJO JOBS.JOB_TITLE%TYPE;
BEGIN
    SELECT J.JOB_TITLE INTO TIPO_TRABAJO FROM JOBS J 
    INNER JOIN EMPLOYEES E ON E.JOB_ID = J.JOB_ID
    WHERE E.EMPLOYEE_ID = 100;

    DBMS_OUTPUT.PUT_LINE(TIPO_TRABAJO);
END;
/*3. PRÁCTICA 3
• Crear una variable de tipo DEPARTMENT_ID y ponerla algún valor, por 
ejemplo 10.
• Visualizar el nombre de ese departamento y el número de empleados 
que tiene, poniendo. Crear dos variables para albergar los valores.*/
SET SERVEROUTPUT ON
DECLARE
    ID_DEPARTAMENTO DEPARTMENTS.DEPARTMENT_ID%TYPE := 10;
    NOMBRE_DEPARTAMENTO DEPARTMENTS.DEPARTMENT_NAME%TYPE;
    EMPLEADOS NUMBER;
    
BEGIN
    SELECT D.DEPARTMENT_NAME, COUNT(*) INTO NOMBRE_DEPARTAMENTO, EMPLEADOS
    FROM DEPARTMENTS D
    INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE D.DEPARTMENT_ID = ID_DEPARTAMENTO
    GROUP BY D.DEPARTMENT_NAME;

    DBMS_OUTPUT.PUT_LINE(NOMBRE_DEPARTAMENTO||' '||EMPLEADOS);
END;

/*4. PRÁCTICA 4
• Mediante dos consultas recuperar el salario máximo y el salario mínimo 
de la empresa e indicar su diferencia*/
SET SERVEROUTPUT ON
DECLARE
     SALARIO_MAX EMPLOYEES.SALARY%TYPE;
     SALARIO_MIN EMPLOYEES.SALARY%TYPE;
     RESULTADO NUMBER;
    
BEGIN
    SELECT MAX(SALARY), MIN(SALARY) INTO SALARIO_MAX, SALARIO_MIN 
    FROM EMPLOYEES;
    
    RESULTADO := SALARIO_MAX-SALARIO_MIN;

    DBMS_OUTPUT.PUT_LINE('SALARIO MAXIMO: '||SALARIO_MAX||' SALARIO MINIMO: '|| SALARIO_MIN||' DIFERENCIA: '||RESULTADO);
END;