create or replace TRIGGER TR1_REGION 
BEFORE INSERT OR UPDATE OR DELETE
ON REGIONS 
FOR EACH ROW
WHEN (NEW.REGION_ID> 1000)
BEGIN 
   IF INSERTING THEN
    :NEW.REGION_NAME:=UPPER(:NEW.REGION_NAME);
     INSERT INTO LOG_TABLE VALUES ('INSERCION',USER);
   END IF;
   IF UPDATING('REGION_NAME') THEN
      :NEW.REGION_NAME:=UPPER(:NEW.REGION_NAME);
      INSERT INTO LOG_TABLE VALUES ('UPDATE DE REGION_NAME', USER);
   END IF;
   IF UPDATING('REGION_ID') THEN
      INSERT INTO LOG_TABLE VALUES ('UPDATE DE REGION_ID', USER);
   END IF;
   IF DELETING  THEN
      INSERT INTO LOG_TABLE VALUES ('DELETE', USER);
   END IF;
   
  /*IF USER <>'HR' THEN
    RAISE_APPLICATION_ERROR(-20000,'SOLO HR PUEDE TRABAJAR EN REGIONS');
  END IF;*/
  
END;

-- PARA SABER EL ESTADO DE UN TRIGGER O DE VARIOS PONEMOS:
SELECT * FROM USER_TRIGGERS;
-- USER_OBJECTS
-- ESTA SE USA PARA COMPILAR UN TRIGGER CUANDO HA SUFRIDO UN CAMBIO
ALTER TRIGGER TR1_REGION COMPILE;

-- USER ERRORS -- ESTA TABLA SE USA PARA VER LOS ERRORES EN LOS OBJETOS

-- ESTA OPCIÓN ES PARA DESACTIVAR EL TRIGGER SI ES LO QUE NECESITAMOS COMO SI EL TRIGGER FUERA DE TIPO ROW Y ESTA MODIFICANDO MILLONES DE REGISTROS
ALTER TRIGGER TR1_REGION COMPILE DISABLE;

-- PARA REACTIVAR EL TRIGGER
ALTER TRIGGER TR1_REGION COMPILE ENABLED;